/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Scene API
 * OpenAPI spec version: 1.0
 */
import type { CreateSceneObjectDtoType } from './createSceneObjectDtoType';
import type { Vector3Dto } from './vector3Dto';

export interface CreateSceneObjectDto {
  /** Shape type */
  type: CreateSceneObjectDtoType;
  position: Vector3Dto;
  scale: Vector3Dto;
  /** Hex color code */
  color: string;
}
