/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Scene API
 * OpenAPI spec version: 1.0
 */

/**
 * Shape type
 */
export type CreateSceneObjectDtoType = typeof CreateSceneObjectDtoType[keyof typeof CreateSceneObjectDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSceneObjectDtoType = {
  cube: 'cube',
  sphere: 'sphere',
} as const;
