/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Scene API
 * OpenAPI spec version: 1.0
 */

export * from './createSceneObjectDto';
export * from './createSceneObjectDtoType';
export * from './updateSceneObjectDto';
export * from './updateSceneObjectDtoType';
export * from './vector3Dto';