/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Scene API
 * OpenAPI spec version: 1.0
 */

export type UpdateSceneObjectDtoType = typeof UpdateSceneObjectDtoType[keyof typeof UpdateSceneObjectDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSceneObjectDtoType = {
  cube: 'cube',
  sphere: 'sphere',
} as const;
